name: CI

on: [push, pull_request, pull_request_review]

jobs:
  build:
    runs-on: ubuntu-16.04
    
    container:
      image: docker://mcr.microsoft.com/dotnet/core/sdk:3.0-alpine     
    steps:
    - uses: actions/checkout@v1
    - name: build and test
      run: |
            dotnet restore src
            dotnet build -f netcoreapp3.0 src
            dotnet test -f netcoreapp3.0 src/SoapCore.Tests

    
      
  
